name: Build on Release

on:
  release:
    types: [published]

jobs:
  build-windows:
    name: Build PS2 Cam Acolyte (Windows)
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: msbuild ps2_cam_acolyte/ps2_cam_acolyte.sln -p:Configuration=Release -p:Platform=x64

    - name: Collect runtime assets
      run: |
        mkdir out
        copy ps2_cam_acolyte\x64\Release\ps2_cam_acolyte.exe out\
        copy ps2_cam_acolyte\x64\Release\SDL2.dll out\
        copy ps2_cam_acolyte\x64\Release\gamecontrollerdb.txt out\

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ps2_cam_acolyte-windows
        path: out/

    - name: Zip output
      run: powershell -c "Compress-Archive -Path out/* -DestinationPath ps2_cam_acolyte-windows.zip"

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: ps2_cam_acolyte-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}